import Head from 'next/head'
import TodoItem from '../components/todoItem'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'

export default function Home() {

  const [items, setItems] = useState([])

  useEffect(() => {
    fetchData()
  }, [])
  

  async function fetchData() {
    axios.get('api/todo')
    .then((res) => {
        console.log(res.data)
        setItems([...res.data])
    })
    .catch((err) => {
      console.log(`error: ${err}`)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Do The Thing</h1>
        {
          items.map((item) => {
            return (
              <div key={item.id}>
                <TodoItem item={item}/>
              </div>
            )
          })
        }
      </main>

      <footer className={styles.footer}>
        feet
      </footer>
    </div>
  )
}
