import Head from 'next/head'
import TodoItem from '../components/todoItem'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'

export default function Home() {

  const [items, setItems] = useState([])
  const [newItem, setNewItem] = useState("")

  useEffect(() => {
    fetchData()
  }, [])
  

  async function fetchData() {
    axios.get('api/todo')
    .then((res) => {
        console.log(res.data)
        setItems([...res.data])
    })
    .catch((err) => {
      console.log(`error: ${err}`)
    })
  }

  function handleInput(e) {
    if (newItem != "") {
      e.preventDefault()
      axios.post('api/todo',{text: newItem})
        .then((res) => {
          setItems([...res.data])
          setNewItem("")
        })
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Do The Thing</h1>
        <form onSubmit={handleInput}>
          <input 
            value={newItem}
            placeholder='Add ToDo Item'
            onChange={(e) => setNewItem(e.target.value)}
          />
        </form>
        {
          items.map((item) => {
            return (
              <div key={item.id}>
                <TodoItem item={item}/>
              </div>
            )
          })
        }
      </main>

      <footer className={styles.footer}>
        feet
      </footer>
    </div>
  )
}
